### ISSUE TITLE
媽咪愛

### ISSUE THREAD

**Issue by nick6969** [iOSTaiwan/jobs#11]
## 公司簡介
媽咪愛是一間成長快速的新創公司，目前有超過 40 萬的用戶，是目前台灣最大的親子社群電商平台。
我們的使命是利用網路的科技，幫助家庭解決生活中遇到的種種問題，陪伴家庭與孩子快樂地成長。

我們的 iOS App，平均 4.8 星，有被 App Store 推薦過
https://goo.gl/TS7H4w

### 我們 Product/Engineering 的團隊文化： 
1. (真正的) 彈性工時與上下班時間，我們更重視的是你的產出和貢獻 
2. 扁平化的組織架構，能發揮自己對產品或技術的想法 
3. 執行 Code Review，交換彼此的意見一起成長 
4. 工程師參與 Design Review 給予意見及協調需求 
5. 每週五團隊技術分享 brown bag session 
6. 每週四公司內部的分享會

### 我們 Product/Engineering 的團隊運作方式:
1. 每天早上 standup meeting，分享自己昨天做了什麼、是否遇到困難需要拿出來討論、和今天預計做什麼，其他時間自己安排
2. 每週技術分享會，大家輪流分享新學習到的技術
3. 期待是能主動提出產品和流程建議的夥伴，我們的團隊蠻就事論事，組織也很扁平，提出的建議只要是有道理、大家有共識，可以很快地執行下去
4. 目前我們 app team 是一位 iOS developer, 一位 Android developer 配置, 接下來希望往三位 app developers的方向前進

## 工作內容
1. 與 PM/Designers 合作，了解團隊優先順序並進行 iOS App 開發、上架、維護 
2. 收集與分析產品相關數據，了解產品該如何改進，與 PM/Designers 進行討論 
3. 吸收新知並動手實作，了解 iOS App 的最佳實踐

## 員工是否需自備工具? (是/否) :
否

## 能力需求
1. 有過 2 年以上開發 iOS APP 的經驗，熟悉 Objective-C or Swift 
2. 熟悉 RESTful API 串接 
3. 熟悉 Git 版本控管 
4. 熟悉 iOS 上架審核流程 
5. 喜歡寫 Code ，覺得在透過網路解決人們生活的難題是一件很酷的事 
6. 想挑戰自我的能力，願意嘗試在快節奏的公司工作 
7. Data-driven，喜歡用數字來驗證工作的成效而不是只是憑感覺 
8. 對 UI 設計敏感度高，注重細節及使用流程，能從使用者角度思考 
9. 溝通能力佳，喜歡團隊合作更勝一人球隊

## 加分
1. 習慣寫 Unit Test
2. 有 CI/CD 經驗
3. 會主動了解新技術並樂於分享

## 撰寫語言
Objective-C / Swift

## 工時
彈性工時與上下班時間，我們更重視的是你的產出和貢獻

## 薪資區間
50K~80K/月，13個月 (視個人經驗和能力而定，若很有經驗薪資可談)

## 福利/推薦項
1. 不需要加班給主管看，能有效率處理完公事準時下班最歡迎 
2. 加入公司滿三個月即有年假，讓你隨時充電一下；另外也有五天的帶薪病假，突然生病不擔心 
3. 每人每月兩次免費按摩的福利，讓大家放鬆一下～ 
4. 你會有一台 Macbook 筆電，陪你更有效率又時尚的工作 
5. 每月一次公司買單的員工聚餐 
6. 我們是媽咪愛，也愛你的媽咪，所以我們會送你「母親節禮物」讓你回家送媽媽 
7. 當然啦，中秋節也有中秋禮物唷 
8. 不定時揪團下午茶 
9. 同事私心超愛的員購優惠 
10. 業績好的時候，會有季獎金～ 
11. 努力達到年度業績目標，很 HIGH 的員工旅遊也是會發生滴～ 
12. 工作地點靠近古亭捷運站，有寬敞的辦公室、舒服的吧台 
13. 我們提供相關課程或演講補助，期待你與公司一起成長

## 公司地址
台北市中正區南昌路二段222號10F

## 聯絡方式
如果對我們公司有興趣，歡迎將履歷 email to: hr@upn.com.tw

**Comment by ArchieR7** [comment]
缺少薪資區間資訊

**Comment by nick6969** [comment]
薪資區間已補上
